### PR TITLE
MDGPS - debug step rule

### PR DESCRIPTION
**Pull request by wmontgomery4**
This PR fixes a bug in the step size adjustment for MDGPS, along with some hyperparameter tweaks to improve 'mjc_mdgps_example' variants.

### CODE REVIEW

**Comment by wmontgomery4** [comment]
I'm running this now on mjc_badmm_example to test the random_seed/quit_on_end stuff. Assuming it works, we'll be ready to merge.

**Comment by wmontgomery4** [comment]
Okay, this is ready to merge. Contains:
- Bug fixes for `stepadjust` in 'MDGPS
- Hyperparameter tweaks for `mjc_mdgps_example`
- Addition of 'random_seed' hyperparam (goes in config), and `--quit` command line flag

I chose to add the `--quit` option as a command line flag rather than a hyperparam since it will mostly be used that way inside scripts and it would be better to not have to include it in the hyperparams.py file. This adds a second argument to the GPSMain object and feels a little hacky, but I think it's the better choice for now.

**Comment by cbfinn** [comment]
LGTM

**Comment by cbfinn** [comment]
By the way, one way to perhaps make the --quit option a bit less hacky, would be to set 

```
hyperparams.config['quit_on_exit'] = args.quit
```

Then, you only have to pass in hyperparams.config, and can read in that option.

Also, this won't quit in the event of an error. I think the only way to quit in the event of an error would be to put error-prone code (or just all of the code) in a try/catch statement.

**Pull request merged**
