### PR TITLE
Rostopicsensor

### PR DESCRIPTION
**Pull request by cdevin**
Changes for the rostopic sensor. The robot plugin was hardcoded to 1 sensor, so to use the rostopic sensor, it must be  changed to 2 sensors. I'm not sure whether that should be pushed to everyone.

### CODE REVIEW

**Comment by cdevin** [comment]
Added a commit to not store images in the gui code.

**Comment by cbfinn** [comment]
Is the memory issue resolved now?

**Comment by cdevin** [comment]
Yes

**Comment by cbfinn** [comment]
Ok, merging now then.

**Pull request merged**
